### PR TITLE
Scaffolded and cleaned up the client

### PR DESCRIPTION
**Pull request by fabianlundgren**
PT Story: https://www.pivotaltracker.com/story/show/143404331

**Changes proposed in this PR:**
-  a scaffolded ionic app
-  add tabs 

**What I have learned working on this feature:**
we learned that its important to work from the correct folder
and it's easy to miss thing's when cleaning an app

**Screenshots:**
screen shot 2017-04-10 at 15 11 20

### CODE REVIEW

**Review by AmberWilkie — CHANGES_REQUESTED** [review]
You guys can use this PR to find files you want to delete (likes photos of these dudes). Sometimes it's easier to see here on Github.

**Comment by tochman** [comment]
Can I please see some screenshots and a more verbose PR description?

**Comment by tochman** [comment]
@AmberWilkie r u okay with this?

**Review by AmberWilkie — APPROVED** [review]

**Comment by AmberWilkie** [comment]
Sorry guys was demoing for the juniors.

**Pull request merged**
