### PR TITLE
List menus on restaurant page

### PR DESCRIPTION
**Pull request by fabianlundgren**
PT Story: https://www.pivotaltracker.com/story/show/143407677

**Changes proposed in this PR:**
- Adds a menu view with menu name, dish, description and price.

**What we have learned working on this feature:**
- How everything is connected with the API etc.

skarmavbild 2017-04-13 kl 11 39 49

### CODE REVIEW

**Comment by tochman** [comment]
To be honest I don't see a need for a separate Menu page since you guys only have one menu per restaurant. This information can be easily displayed on the restaurant show page. What I would suggest it to start working on a dish show page so you can display more detailed information about a dish in order to inform the customer.

**Comment by fottander** [comment]
Ok @tochman I´m confused. 
In the middle of the project we are changing the way the app is gonna look like? 
Isn´t the mobile app supposed to have the same structure as the website? 
Also the instructions have given good directions on how the pages are supposed to look like: 
http://class.craftacademy.se/courses/course-v1:CraftAcademy+CA-CAMP+2017_1/courseware/8fb7660e42b640cda07d639bce95282e/7a90f660128b42c79d61cf85a5146e2a/

**Review by casperjureskog — APPROVED** [review]
looks god to me

**Comment by tochman** [comment]
I was merely making a suggestion Felix. But this calls for a discussion on how the data is presented to the user. If you should copy the page structure of the web app into you mobile app? I would say not necessarily.

**Comment by fottander** [comment]
Yeah sure I understand. I just wasn´t sure what best practices are when you are building a mobile app based on your web app. But alright good to know.

**Pull request merged**
